weights: yolov5s6.pt
cfg: ''
data: /kaggle/working/gbr.yaml
hyp: /kaggle/working/hyp.yaml
epochs: 16
batch_size: 4
imgsz: 3000
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: ''
multi_scale: false
single_cls: false
optimizer: Adam
sync_bn: false
workers: 8
project: great-barrier-reef
name: yolov5s6-dim3000-fold1-epoch16
exist_ok: true
quad: false
cos_lr: false
label_smoothing: 0.0
patience: 100
freeze:
- 0
save_period: -1
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: great-barrier-reef/yolov5s6-dim3000-fold1-epoch16
